{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':u'bgTemplate',
          'size':(600, 510),

         'strings': {
         },

         'components': [

{'type':'Button', 
    'name':'ButtonDelBidder', 
    'position':(172, 277), 
    'size':(65, -1), 
    'backgroundColor':(255, 128, 128, 255), 
    'enabled':False, 
    'label':'ButtonDelBidder', 
    },

{'type':'Button', 
    'name':'ButtonFixBidder', 
    'position':(248, 277), 
    'size':(65, -1), 
    'backgroundColor':(255, 255, 128, 255), 
    'enabled':False, 
    'label':'ButtonFixBidder', 
    },

{'type':'StaticText', 
    'name':'StaticTextDataFileName', 
    'position':(403, 15), 
    'text':'StaticTextDataFileName', 
    },

{'type':'Button', 
    'name':'ButtonNewFile', 
    'position':(19, 310), 
    'size':(65, -1), 
    'label':'ButtonNewFile', 
    },

{'type':'Button', 
    'name':'ButtonAddBidder', 
    'position':(323, 277), 
    'size':(65, -1), 
    'backgroundColor':(128, 255, 128, 255), 
    'enabled':False, 
    'label':'ButtonAddBidder', 
    },

{'type':'Button', 
    'name':'ButtonOpen', 
    'position':(96, 310), 
    'size':(65, -1), 
    'label':'ButtonOpen', 
    },

{'type':'TextArea', 
    'name':'TextAreaLog', 
    'position':(19, 344), 
    'size':(558, 124), 
    'editable':False, 
    },

{'type':'Button', 
    'name':'ButtonSendAll', 
    'position':(323, 310), 
    'size':(65, -1), 
    'enabled':False, 
    'label':'ButtonSendAll', 
    },

{'type':'Button', 
    'name':'ButtonSendSingle', 
    'position':(248, 310), 
    'size':(65, -1), 
    'enabled':False, 
    'label':'ButtonSendSingle', 
    },

{'type':'Button', 
    'name':'ButtonConnect', 
    'position':(172, 310), 
    'size':(65, -1), 
    'enabled':False, 
    'label':'ButtonConnect', 
    },

{'type':'List', 
    'name':'ListBidders', 
    'position':(398, 33), 
    'size':(179, 303), 
    'items':[], 
    },

{'type':'TextField', 
    'name':'TextFieldBidderID', 
    'position':(289, 9), 
    'size':(-1, 28), 
    'backgroundColor':(255, 128, 64, 255), 
    'enabled':False, 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 14}, 
    },

{'type':'StaticText', 
    'name':'StaticTextBidderID', 
    'position':(245, 11), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 14}, 
    'text':'StaticTextBidderID', 
    },

{'type':'TextField', 
    'name':'TextFieldCreditCardType', 
    'position':(319, 242), 
    'size':(70, -1), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextCreditCardType', 
    'position':(252, 245), 
    'size':(60, -1), 
    'text':'StaticTextCreditCardType', 
    },

{'type':'TextField', 
    'name':'TextFieldCreditCardID', 
    'position':(88, 242), 
    'size':(150, -1), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextCreditCardID', 
    'position':(20, 245), 
    'size':(60, -1), 
    'text':'StaticTextCreditCardID', 
    },

{'type':'TextField', 
    'name':'TextFieldBankContactTel', 
    'position':(256, 217), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextBankContactTel', 
    'position':(201, 220), 
    'size':(48, -1), 
    'text':'StaticTextBankContactTel', 
    },

{'type':'TextField', 
    'name':'TextFieldBankContact', 
    'position':(88, 217), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextBankContact', 
    'position':(20, 220), 
    'size':(60, -1), 
    'text':'StaticTextBankContact', 
    },

{'type':'TextField', 
    'name':'TextFieldBankAcc', 
    'position':(50, 192), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextBankAcc', 
    'position':(20, 195), 
    'size':(24, -1), 
    'text':'StaticTextBankAcc', 
    },

{'type':'TextField', 
    'name':'TextFieldBank', 
    'position':(102, 167), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextBank', 
    'position':(20, 170), 
    'size':(78, -1), 
    'text':'StaticTextBank', 
    },

{'type':'TextField', 
    'name':'TextFieldEMail', 
    'position':(54, 142), 
    'size':(150, -1), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextEMail', 
    'position':(20, 145), 
    'size':(30, -1), 
    'text':'StaticTextEMail', 
    },

{'type':'TextField', 
    'name':'TextFieldAddress', 
    'position':(50, 117), 
    'size':(304, -1), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextAddress', 
    'position':(20, 120), 
    'size':(24, -1), 
    'text':'StaticTextAddress', 
    },

{'type':'TextField', 
    'name':'TextFieldFax', 
    'position':(194, 92), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextFax', 
    'position':(162, 95), 
    'size':(24, -1), 
    'text':'StaticTextFax', 
    },

{'type':'TextField', 
    'name':'TextFieldCareerTitle', 
    'position':(239, 42), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextCareerTitle', 
    'position':(209, 45), 
    'size':(24, -1), 
    'text':'StaticTextCareerTitle', 
    },

{'type':'TextField', 
    'name':'TextFieldTel', 
    'position':(50, 92), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextTel', 
    'position':(20, 95), 
    'size':(24, -1), 
    'text':'StaticTextTel', 
    },

{'type':'TextField', 
    'name':'TextFieldIDNumber', 
    'position':(116, 67), 
    'size':(92, -1), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextIDNumber', 
    'position':(20, 70), 
    'size':(90, -1), 
    'text':'StaticTextIDNumber', 
    },

{'type':'TextField', 
    'name':'TextFieldCompany', 
    'position':(75, 42), 
    'size':(120, -1), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextCompany', 
    'position':(20, 45), 
    'size':(48, -1), 
    'text':'StaticTextCompany', 
    },

{'type':'TextField', 
    'name':'TextFieldName', 
    'position':(88, 16), 
    'size':(120, -1), 
    'enabled':False, 
    },

{'type':'StaticText', 
    'name':'StaticTextName', 
    'position':(20, 20), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 9}, 
    'text':'StaticTextName', 
    },

] # end components
} # end background
] # end backgrounds
} }
