{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':u'bgTemplate',
          'size':(667, 550),

         'strings': {
         },

         'components': [

{'type':'StaticText', 
    'name':'StaticTextPackImgState', 
    'position':(410, 312), 
    'size':(80, -1), 
    'text':'StaticTextPackImgState', 
    },

{'type':'StaticText', 
    'name':'StaticTextBuildImgState', 
    'position':(296, 312), 
    'size':(80, -1), 
    'text':'StaticTextBuildImgState', 
    },

{'type':'TextField', 
    'name':'TextFieldLotNO', 
    'position':(562, 356), 
    'size':(79, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldItemPS', 
    'position':(534, 330), 
    'size':(107, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldRemain', 
    'position':(562, 304), 
    'size':(79, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldReservePrice', 
    'position':(584, 278), 
    'size':(57, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldSpec', 
    'position':(562, 252), 
    'size':(50, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldItemNum', 
    'position':(534, 226), 
    'size':(30, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextLotNO', 
    'position':(506, 359), 
    'text':'StaticTextLotNO', 
    },

{'type':'StaticText', 
    'name':'StaticTextItemPS', 
    'position':(506, 333), 
    'text':'StaticTextItemPS', 
    },

{'type':'StaticText', 
    'name':'StaticTextRemain', 
    'position':(506, 307), 
    'text':'StaticTextRemain', 
    },

{'type':'StaticText', 
    'name':'StaticTextReservePrice', 
    'position':(506, 281), 
    'text':'StaticTextReservePrice', 
    },

{'type':'StaticText', 
    'name':'StaticTextSpec', 
    'position':(506, 255), 
    'text':'StaticTextSpec', 
    },

{'type':'StaticText', 
    'name':'StaticTextItemNum', 
    'position':(506, 229), 
    'size':(54, -1), 
    'text':'StaticTextItemNum', 
    },

{'type':'Button', 
    'name':'ButtonSetPackImg', 
    'position':(461, 250), 
    'size':(40, -1), 
    'backgroundColor':(0, 128, 255, 255), 
    'label':'ButtonSetPackImg', 
    },

{'type':'Button', 
    'name':'ButtonSetBuildImg', 
    'position':(347, 250), 
    'size':(40, -1), 
    'backgroundColor':(0, 128, 255, 255), 
    'label':'ButtonSetBuildImg', 
    },

{'type':'StaticText', 
    'name':'StaticTextPackImg', 
    'position':(400, 255), 
    'size':(76, -1), 
    'text':'StaticTextPackImg', 
    },

{'type':'StaticText', 
    'name':'StaticTextBuildImg', 
    'position':(286, 255), 
    'size':(88, -1), 
    'text':'StaticTextBuildImg', 
    },

{'type':'TextField', 
    'name':'TextFieldItemName', 
    'position':(360, 226), 
    'size':(141, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextItemName', 
    'position':(286, 229), 
    'size':(96, -1), 
    'text':'StaticTextItemName', 
    },

{'type':'BitmapCanvas', 
    'name':'BitmapCanvasPack', 
    'position':(400, 273), 
    'size':(100, 100), 
    'backgroundColor':(255, 255, 255, 255), 
    },

{'type':'BitmapCanvas', 
    'name':'BitmapCanvasBuild', 
    'position':(286, 273), 
    'size':(100, 100), 
    'backgroundColor':(255, 255, 255, 255), 
    },

{'type':'StaticText', 
    'name':'StaticTextNTDperItem4', 
    'position':(589, 172), 
    'size':(38, -1), 
    'text':'StaticTextNTDperItem4', 
    },

{'type':'StaticText', 
    'name':'StaticTextNTDperItem3', 
    'position':(589, 194), 
    'size':(38, -1), 
    'text':'StaticTextNTDperItem3', 
    },

{'type':'StaticText', 
    'name':'StaticTextNTDperItem2', 
    'position':(396, 194), 
    'size':(38, -1), 
    'text':'StaticTextNTDperItem2', 
    },

{'type':'StaticText', 
    'name':'StaticTextNTDperItem1', 
    'position':(251, 194), 
    'size':(38, -1), 
    'text':'StaticTextNTDperItem1', 
    },

{'type':'StaticText', 
    'name':'StaticTextNTDperItem5', 
    'position':(587, 150), 
    'size':(38, -1), 
    'text':'StaticTextNTDperItem5', 
    },

{'type':'StaticText', 
    'name':'StaticTextPercent3', 
    'position':(424, 172), 
    'size':(13, -1), 
    'text':'StaticTextPercent3', 
    },

{'type':'StaticText', 
    'name':'StaticTextPercent2', 
    'position':(279, 172), 
    'size':(13, -1), 
    'text':'StaticTextPercent2', 
    },

{'type':'StaticText', 
    'name':'StaticTextPercent1', 
    'position':(279, 150), 
    'size':(13, -1), 
    'text':'StaticTextPercent1', 
    },

{'type':'StaticText', 
    'name':'StaticTextPercent4', 
    'position':(424, 150), 
    'size':(13, -1), 
    'text':'StaticTextPercent4', 
    },

{'type':'StaticText', 
    'name':'StaticTextItemList', 
    'position':(154, 218), 
    'text':'StaticTextItemList', 
    },

{'type':'Button', 
    'name':'ButtonDelItem', 
    'position':(232, 351), 
    'size':(40, -1), 
    'backgroundColor':(255, 128, 128, 255), 
    'label':'ButtonDelItem', 
    },

{'type':'Button', 
    'name':'ButtonFixItem', 
    'position':(192, 352), 
    'size':(40, -1), 
    'backgroundColor':(255, 255, 128, 255), 
    'label':'ButtonFixItem', 
    },

{'type':'Button', 
    'name':'ButtonAddItem', 
    'position':(152, 352), 
    'size':(40, -1), 
    'backgroundColor':(128, 255, 128, 255), 
    'label':'ButtonAddItem', 
    },

{'type':'List', 
    'name':'ListItem', 
    'position':(152, 237), 
    'size':(120, 109), 
    'items':[], 
    },

{'type':'TextField', 
    'name':'TextFieldIdentifyFee', 
    'position':(542, 191), 
    'size':(45, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldFireFee', 
    'position':(542, 169), 
    'size':(45, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldFrameFee', 
    'position':(540, 147), 
    'size':(45, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextIdentifyFee', 
    'position':(443, 194), 
    'text':'StaticTextIdentifyFee', 
    },

{'type':'StaticText', 
    'name':'StaticTextFireFee', 
    'position':(443, 172), 
    'text':'StaticTextFireFee', 
    },

{'type':'StaticText', 
    'name':'StaticTextFrameFee', 
    'position':(443, 150), 
    'text':'StaticTextFrameFee', 
    },

{'type':'StaticText', 
    'name':'StaticTextOtherFee', 
    'position':(443, 128), 
    'text':'StaticTextOtherFee', 
    },

{'type':'TextField', 
    'name':'TextFieldIfNDealedPictureFee', 
    'position':(349, 191), 
    'size':(45, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldIfNDealedServiceFee', 
    'position':(399, 169), 
    'size':(23, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldIfNDealedInsuranceFee', 
    'position':(399, 147), 
    'size':(23, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextIfNDealedPictureFee', 
    'position':(298, 194), 
    'size':(54, -1), 
    'text':'StaticTextIfNDealedPictureFee', 
    },

{'type':'StaticText', 
    'name':'StaticTextIfNDealedServiceFee', 
    'position':(298, 172), 
    'size':(103, -1), 
    'text':'StaticTextIfNDealedServiceFee', 
    },

{'type':'StaticText', 
    'name':'StaticTextIfNDealedInsuranceFee', 
    'position':(298, 150), 
    'size':(103, -1), 
    'text':'StaticTextIfNDealedInsuranceFee', 
    },

{'type':'StaticText', 
    'name':'StaticTextIfNDealed', 
    'position':(298, 128), 
    'text':'StaticTextIfNDealed', 
    },

{'type':'TextField', 
    'name':'TextFieldIfDealedPictureFee', 
    'position':(204, 191), 
    'size':(45, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldIfDealedServiceFee', 
    'position':(254, 169), 
    'size':(23, -1), 
    },

{'type':'TextField', 
    'name':'TextFieldIfDealedInsuranceFee', 
    'position':(254, 147), 
    'size':(23, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextIfDealedPictureFee', 
    'position':(153, 194), 
    'size':(54, -1), 
    'text':'StaticTextIfDealedPictureFee', 
    },

{'type':'StaticText', 
    'name':'StaticTextIfDealedServiceFee', 
    'position':(152, 172), 
    'size':(103, -1), 
    'text':'StaticTextIfDealedServiceFee', 
    },

{'type':'StaticText', 
    'name':'StaticTextIfDealed', 
    'position':(153, 128), 
    'text':'StaticTextIfDealed', 
    },

{'type':'StaticText', 
    'name':'StaticTextDealerList', 
    'position':(20, 128), 
    'text':'StaticTextDealerList', 
    },

{'type':'TextField', 
    'name':'TextFieldPostID', 
    'position':(584, 97), 
    'size':(60, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextPostID', 
    'position':(555, 100), 
    'text':'StaticTextPostID', 
    },

{'type':'TextField', 
    'name':'TextFieldBankAcc', 
    'position':(315, 97), 
    'size':(210, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextBankAcc', 
    'position':(266, 100), 
    'text':'StaticTextBankAcc', 
    },

{'type':'TextField', 
    'name':'TextFieldBankName', 
    'position':(71, 97), 
    'size':(180, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextBankName', 
    'position':(20, 100), 
    'text':'StaticTextBankName', 
    },

{'type':'TextField', 
    'name':'TextFieldContractID', 
    'position':(491, 13), 
    'size':(153, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextContractID', 
    'position':(435, 16), 
    'text':'StaticTextContractID', 
    },

{'type':'Button', 
    'name':'ButtonDelDealer', 
    'position':(99, 352), 
    'size':(40, -1), 
    'backgroundColor':(255, 128, 128, 255), 
    'label':'ButtonDelDealer', 
    },

{'type':'Button', 
    'name':'ButtonFixDealer', 
    'position':(59, 352), 
    'size':(40, -1), 
    'backgroundColor':(255, 255, 128, 255), 
    'label':'ButtonFixDealer', 
    },

{'type':'Button', 
    'name':'ButtonAddDealer', 
    'position':(19, 352), 
    'size':(40, -1), 
    'backgroundColor':(128, 255, 128, 255), 
    'label':'ButtonAddDealer', 
    },

{'type':'TextArea', 
    'name':'TextAreaLog', 
    'position':(19, 381), 
    'size':(622, 124), 
    'editable':False, 
    },

{'type':'List', 
    'name':'ListDealer', 
    'position':(19, 146), 
    'size':(120, 200), 
    'items':[], 
    },

{'type':'TextField', 
    'name':'TextFieldAddress', 
    'position':(71, 70), 
    'size':(421, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextAddress', 
    'position':(20, 72), 
    'size':(60, -1), 
    'text':'StaticTextAddress', 
    },

{'type':'TextField', 
    'name':'TextFieldFax', 
    'position':(544, 69), 
    },

{'type':'StaticText', 
    'name':'StaticTextFax', 
    'position':(515, 72), 
    'size':(24, -1), 
    'text':'StaticTextFax', 
    },

{'type':'TextField', 
    'name':'TextFieldTel', 
    'position':(544, 41), 
    },

{'type':'StaticText', 
    'name':'StaticTextTel', 
    'position':(515, 44), 
    'size':(24, -1), 
    'text':'StaticTextTel', 
    },

{'type':'TextField', 
    'name':'TextFieldCardID', 
    'position':(417, 41), 
    'size':(92, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextCardID', 
    'position':(366, 44), 
    'size':(90, -1), 
    'text':'StaticTextCardID', 
    },

{'type':'TextField', 
    'name':'TextFieldCountry', 
    'position':(273, 41), 
    'size':(66, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextCountry', 
    'position':(246, 44), 
    'size':(48, -1), 
    'text':'StaticTextCountry', 
    },

{'type':'StaticText', 
    'name':'StaticTextName', 
    'position':(20, 44), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 9}, 
    'text':'StaticTextName', 
    },

{'type':'TextField', 
    'name':'TextFieldName', 
    'position':(60, 41), 
    'size':(166, -1), 
    },

{'type':'StaticText', 
    'name':'StaticTextIfDealedInsuranceFee', 
    'position':(153, 150), 
    'size':(102, -1), 
    'text':'StaticTextIfDealedInsuranceFee', 
    },

] # end components
} # end background
] # end backgrounds
} }
